### ISSUE TITLE
Add new prdoduct bug

### ISSUE THREAD

**Issue by Nicole-Cuervo** [sebastiantrianamartinez/sells-and-billing-system-python#1]
When I try to add new products, the app doesn't refresh, I gotta restart the app, then work.
May you can create a script for auto-update UI and data after add products.
Thanks.

**Comment by sebastiantrianamartinez** [comment]
We've updated the app, now after add a product, the UI will update, then you can use the new product in the same execution of app.
Thanks for help us.
